package lt.vu.helloworldapp;

import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;import android.graphics.Color;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);

        // Get references to the UI elements
        TextView textViewMessage = findViewById(R.id.textViewMessage);
        Button buttonChangeText = findViewById(R.id.buttonChangeText);

        // Change the TextView text when the button is clicked
        buttonChangeText.setOnClickListener(v ->
                textViewMessage.setText("Welcome to Android!")
        );
        Button buttonChangeColor = findViewById(R.id.buttonChangeColor);

        buttonChangeColor.setOnClickListener(v -> {
            textViewMessage.setTextColor(Color.RED);
        });
        Button buttonChangeBackground = findViewById(R.id.buttonChangeBackground);

        buttonChangeBackground.setOnClickListener(v -> {
            findViewById(R.id.main).setBackgroundColor(Color.YELLOW);
        });

        // Keep the code generated by Android Studio
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });
    }
}